#!/usr/bin/env bash
while read line; do
    userid=$(echo "$line" | cut -d: -f3)
    username=$(echo "$line" | cut -d: -f1)
    homepath=$(echo "$line" | cut -d: -f6)
    echo "$username:$userid:$homepath"
done < /etc/passwd

