#!/usr/bin/env bash
#this implements the existence of a file and whether it is a regular file and is empty or not 

i="school"
if [ -e "school" ]
 then 
     echo "school files exists"
      if [ -s "school" ]
        then
          echo "school file is not empty"
       else
         echo "school file is empty"
       fi 
       
       if [ -f "school" ]
         then 
            echo "school file is a regular file"
       else
            echo " "
       fi 
 else
      echo "school file does not exists"
fi
